/*
 * This file is generated by jOOQ.
*/
package com.assets.portfolio.data.loader.mysql.entities;


import com.assets.portfolio.data.loader.mysql.entities.tables.DailyQuotes;
import com.assets.portfolio.data.loader.mysql.entities.tables.records.DailyQuotesRecord;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>portfolio</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DailyQuotesRecord> KEY_DAILY_QUOTES_PRIMARY = UniqueKeys0.KEY_DAILY_QUOTES_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<DailyQuotesRecord> KEY_DAILY_QUOTES_PRIMARY = createUniqueKey(DailyQuotes.DAILY_QUOTES, "KEY_daily_quotes_PRIMARY", DailyQuotes.DAILY_QUOTES.ID);
    }
}
