/*
 * This file is generated by jOOQ.
*/
package com.assets.portfolio.data.loader.mysql.entities;


import com.assets.portfolio.data.loader.mysql.entities.tables.DailyQuotes;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Portfolio extends SchemaImpl {

    private static final long serialVersionUID = 1909937749;

    /**
     * The reference instance of <code>portfolio</code>
     */
    public static final Portfolio PORTFOLIO = new Portfolio();

    /**
     * The table <code>portfolio.daily_quotes</code>.
     */
    public final DailyQuotes DAILY_QUOTES = com.assets.portfolio.data.loader.mysql.entities.tables.DailyQuotes.DAILY_QUOTES;

    /**
     * No further instances allowed
     */
    private Portfolio() {
        super("portfolio", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            DailyQuotes.DAILY_QUOTES);
    }
}
