/*
 * This file is generated by jOOQ.
*/
package com.assets.portfolio.data.loader.mysql.entities;


import com.assets.portfolio.data.loader.mysql.entities.tables.DailyQuotes;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in portfolio
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>portfolio.daily_quotes</code>.
     */
    public static final DailyQuotes DAILY_QUOTES = com.assets.portfolio.data.loader.mysql.entities.tables.DailyQuotes.DAILY_QUOTES;
}
